# Generated by Django 6.1.1 on 2026-09-10 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Management_System',
            fields=[
                ('Emp_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('City', models.CharField(max_length=45)),
                ('Salary', models.IntegerField()),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'employee_details',
                'managed': False,
            },
        ),
    ]
