# Generated by Django 6.1 on 2026-09-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=1000)),
                ('Mentor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Students_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Class', models.CharField(max_length=50)),
                ('Course', models.CharField(max_length=100)),
                ('Mentor', models.CharField(max_length=100)),
            ],
        ),
    ]
