# Generated by Django 6.1 on 2026-09-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_details',
            name='MobileNo',
            field=models.CharField(default=9284488740, max_length=15),
            preserve_default=False,
        ),
    ]
